apiVersion: v1
kind: Service
metadata:
  name: xrp-service
spec:
  selector:
    app: xrp_node
  ports:
    - name: public-port
      protocol: TCP
      port: 51234
      targetPort: 51234
    - name: peer-port
      protocol: TCP
      port: 51235
      targetPort: 51235
  type: LoadBalancer
